version: '3.8'

services:
  task-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog-master.yaml
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: task-management-db
    ports:
      - "${DB_PORT}:5432"
    environment:

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: