version: '3.8'

services:
  task-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_management_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:/db/changelog-master.yaml
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: task-management-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_management_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    tmpfs:
      - /var/lib/postgresql/data
    restart: always

volumes:
  db_data: